'use server'

import { createClient } from '@/lib/supabase/server'
import { interpretQuery } from '@/lib/gemini/query'
import { executeQuery } from '@/lib/gemini/query-executor'
import { searchByImageReferences } from '@/lib/gemini/image-search'
import { tryFastPath } from '@/lib/gemini/query-fast-path'
import type { ChatMessage, Image } from '@/types/domain'
import type { Json, TablesInsert } from '@/lib/supabase/types'
import type { QueryPlan, QueryFilter } from '@/lib/gemini/query'
import type { SupabaseClient } from '@supabase/supabase-js'

const CHAT_HISTORY_PAGE_SIZE = 50

export type SendMessageResult = {
  userMessage: ChatMessage
  assistantMessage: ChatMessage
  images: Image[]
  total: number
  // Null when image-as-prompt path was used (no structured filter to show).
  interpretedFilter: QueryPlan | null
  // Contextual follow-up suggestions generated by the query interpreter.
  followups: string[]
}

export async function sendMessage(
  rollId: string,
  text: string,
  referenceImageIds?: string[],
  activeFilters?: QueryFilter[],
): Promise<SendMessageResult> {
  const supabase = await createClient()

  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) throw new Error('Unauthorized')

  const userRow: TablesInsert<'chat_messages'> = {
    roll_id: rollId,
    user_id: user.id,
    role: 'user',
    content: text,
  }

  const { data: savedUserMsg, error: userMsgError } = await supabase
    .from('chat_messages')
    .insert(userRow as never)
    .select()
    .single()

  if (userMsgError || !savedUserMsg) {
    throw new Error(`Failed to save user message: ${userMsgError?.message}`)
  }

  let resultImages: Image[]
  let total: number
  let interpretedFilter: QueryPlan | null = null

  const hasReferenceImages = referenceImageIds && referenceImageIds.length > 0

  if (hasReferenceImages) {
    resultImages = await searchByImageReferences(referenceImageIds, rollId, text || undefined)
    total = resultImages.length
  } else {
    const t0 = Date.now()
    const fastPathResult = tryFastPath(text)

    let plan: QueryPlan
    let telemetryPath: string

    if (fastPathResult) {
      plan = fastPathResult.plan
      telemetryPath = `fast_path_hit:${fastPathResult.matched}`
    } else {
      try {
        plan = await interpretQuery(text)
        telemetryPath = 'llm'
      } catch {
        // interpretQuery already degrades gracefully, but this guard handles unexpected throws
        plan = { filters: [], semantic_search: text, sort: null, limit: 50, clarification_note: null, followups: [] }
        telemetryPath = 'fallback'
      }
    }

    console.log(`[chat] path=${telemetryPath} latency=${Date.now() - t0}ms query="${text.slice(0, 60)}"`)

    // Merge client-held active filters with new filters from this query.
    // Deduplication prevents the same filter appearing twice when the user
    // refines a search that already has that filter active.
    const mergedFilters = deduplicateFilters([...(activeFilters ?? []), ...plan.filters])
    interpretedFilter = { ...plan, filters: mergedFilters }
    const queryResult = await executeQuery(interpretedFilter, rollId)
    resultImages = queryResult.images
    total = queryResult.total
  }

  const resultImageIds = resultImages.map(img => img.id)
  const savedAssistantMsg = await saveAssistantMessage(
    supabase,
    rollId,
    user.id,
    buildAssistantContent(total, interpretedFilter),
    resultImageIds,
    interpretedFilter,
  )

  return {
    userMessage: savedUserMsg as ChatMessage,
    assistantMessage: savedAssistantMsg,
    images: resultImages,
    total,
    interpretedFilter,
    followups: interpretedFilter?.followups ?? [],
  }
}

// Returns a page of chat history in chronological order (oldest first).
// Page 0 = most recent CHAT_HISTORY_PAGE_SIZE messages.
// Page 1 = the next-older page, to be prepended before page 0 in the UI.
// Use a before_timestamp cursor for reliable real-time pagination when new
// messages arrive during a session; this offset-based variant is safe for
// initial load where the history is stable.
export async function getChatHistory(
  rollId: string,
  page = 0,
): Promise<ChatMessage[]> {
  const supabase = await createClient()

  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) throw new Error('Unauthorized')

  // Fetch newest-first so the DB can use the (roll_id, created_at) index
  // efficiently. Reverse before returning so callers always receive
  // chronological order regardless of which page they requested.
  const { data, error } = await supabase
    .from('chat_messages')
    .select('*')
    .eq('roll_id', rollId)
    .eq('user_id', user.id)
    .order('created_at', { ascending: false })
    .range(page * CHAT_HISTORY_PAGE_SIZE, (page + 1) * CHAT_HISTORY_PAGE_SIZE - 1)

  if (error) throw new Error(`Failed to fetch chat history: ${error.message}`)

  return ((data ?? []) as ChatMessage[]).reverse()
}

export async function getLastRollState(rollId: string): Promise<{
  resultImageIds: string[] | null
  activePlan: import('@/lib/gemini/query').QueryPlan | null
}> {
  const supabase = await createClient()
  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) return { resultImageIds: null, activePlan: null }

  const { data } = await supabase
    .from('chat_messages')
    .select('result_image_ids, interpreted_filter')
    .eq('roll_id', rollId)
    .eq('user_id', user.id)
    .eq('role', 'assistant')
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle()

  return {
    resultImageIds: (data?.result_image_ids as string[] | null) ?? null,
    activePlan: (data?.interpreted_filter as import('@/lib/gemini/query').QueryPlan | null) ?? null,
  }
}

export type FilterMod =
  | { type: 'remove'; index: number }
  | { type: 'add'; filter: QueryFilter }

export type RerunResult = {
  assistantMessage: ChatMessage
  images: Image[]
  total: number
  interpretedFilter: QueryPlan
}

export async function rerunWithModifiedFilters(
  rollId: string,
  existingPlan: QueryPlan,
  modifications: FilterMod[],
): Promise<RerunResult> {
  const supabase = await createClient()

  const { data: { user }, error: authError } = await supabase.auth.getUser()
  if (authError || !user) throw new Error('Unauthorized')

  let filters = [...existingPlan.filters]

  // Process removals in reverse index order so earlier removals don't shift later indices.
  const removals = modifications
    .filter((m): m is Extract<FilterMod, { type: 'remove' }> => m.type === 'remove')
    .sort((a, b) => b.index - a.index)

  for (const mod of removals) {
    // Guard against out-of-bounds indices from client — negative splice removes from tail.
    if (mod.index < 0 || mod.index >= filters.length) continue
    filters.splice(mod.index, 1)
  }

  for (const mod of modifications) {
    if (mod.type === 'add') filters.push(mod.filter)
  }

  const modifiedPlan: QueryPlan = { ...existingPlan, filters }
  const queryResult = await executeQuery(modifiedPlan, rollId)
  const resultImageIds = queryResult.images.map(img => img.id)

  const savedMsg = await saveAssistantMessage(
    supabase,
    rollId,
    user.id,
    buildAssistantContent(queryResult.total, modifiedPlan),
    resultImageIds,
    modifiedPlan,
  )

  return {
    assistantMessage: savedMsg,
    images: queryResult.images,
    total: queryResult.total,
    interpretedFilter: modifiedPlan,
  }
}

async function saveAssistantMessage(
  supabase: SupabaseClient,
  rollId: string,
  userId: string,
  content: string,
  resultImageIds: string[],
  interpretedFilter: QueryPlan | null,
): Promise<ChatMessage> {
  const row: TablesInsert<'chat_messages'> = {
    roll_id: rollId,
    user_id: userId,
    role: 'assistant',
    content,
    result_image_ids: resultImageIds.length > 0 ? resultImageIds : null,
    interpreted_filter: interpretedFilter ? (interpretedFilter as unknown as Json) : null,
  }

  const { data, error } = await supabase
    .from('chat_messages')
    .insert(row as never)
    .select()
    .single()

  if (error || !data) throw new Error(`Failed to save assistant message: ${error?.message}`)
  return data as ChatMessage
}

// Two filters are considered duplicates when they target the same field+operator+value.
// Keeps the last occurrence so newer query filters win on exact conflicts.
function deduplicateFilters(filters: QueryFilter[]): QueryFilter[] {
  const seen = new Map<string, number>()
  filters.forEach((f, i) => {
    seen.set(`${f.field}|${f.operator}|${JSON.stringify(f.value)}`, i)
  })
  return filters.filter((_, i) => [...seen.values()].includes(i))
}

function buildAssistantContent(resultCount: number, plan: QueryPlan | null): string {
  if (resultCount === 0) {
    if (plan?.clarification_note) return plan.clarification_note
    return "I couldn't find any images matching your query. Try broadening the description or using different keywords."
  }

  if (plan?.clarification_note) {
    return `${plan.clarification_note} Found ${resultCount} image${resultCount === 1 ? '' : 's'}.`
  }

  return `Found ${resultCount} image${resultCount === 1 ? '' : 's'}.`
}
